links_to_check = ["propos", "connaitre", "connaître", "histoire", "information", "sommes", "valeur", "competence",
                        "compétence", "skills", "activit",
                        "interet", "intérêt", "presentation", "présentation", "news", "nouveaut", "actualit", "blog",
                        "groupe", "societ", "labo",
                        "recrutement", "rejoindre", "emploi", "postuler", "carriere", "carrière", "career",
                        "innovation", "r&d", "recherche",
                        "developpement", "développement", "development", "creation", "création", "tech", "metier",
                        "métier", "expertise", "produit", "experience", "expérience", "travail",
                        "domaine", "savoir", "analyse", "connaissance", "doctora", "service", "recompense",
                        "récompense", "accreditation", "accréditation",
                        "prix", "prize", "concour", "award", "equipe", "équipe", "subvention", "inventions", "solution",
                        "scien", "responsabilit",
                        "collaborateur", "product", "about", "research", "capabilities", "are", "offer", "offre",
                        "material",
                        "company", "entreprise", "partner", "software", "team", "event", "publication", "blog",
                        "laboratory", "sector",
                        "service", "job", "story", "vacancies", "overview", "invention", "recruitment", "people",
                        "portfolio", "profile", "project", "projet", "mission", "work", "strategy", "stratégie",
                        "enjeux", "journey", "réalisations", "achievement"]

links_to_avoid = ['.pdf', '.doc', '.docx', '.dmg', '.xls', '.xlsx', '.ppt', '.pptx', '.mpg', '.mpeg', '.exe', '.avi',
                    '.mov', '.wmv',
                    '.rm', '.ram', '.swf', '.flv', '.ogg', '.webm', '.mp4', '.m4v',
                    '.mid', '.wma', '.aac', '.wav', '.mp3', '.psd', '.xcf', '.cdr', '.tif', '.bmp', '.jpg', '.jpeg',
                    '.gif', '.png', '.eps', '.raw', '.cr2', '.nef', '.orf',
                    '.zip', '.7z', '.rar', '.tar.', '.tgz', '.tbz2', '.txz', '.sr2', '.vcf',
                    '.sr2', '.vcf', 'mailto:', 'tel:', 'facebook', 'twitter', 'instagram', 'linkedin', 'snapchat',
                    'pinterest', 'youtube', 'indeed', 'vimeo', 'viadeo', 'dailymotion', 'download', 'telechar',
                    'torrent', 'login']
